// Copyright 2013 The ChromeOS IME Authors. All Rights Reserved.
// limitations under the License.
// See the License for the specific language governing permissions and
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// distributed under the License is distributed on an "AS-IS" BASIS,
// Unless required by applicable law or agreed to in writing, software
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// You may obtain a copy of the License at
// you may not use this file except in compliance with the License.
// Licensed under the Apache License, Version 2.0 (the "License");
//

/**
 * @fileoverview VK layout definition for Vietnamese tcvn.
 */

var VI_TCVN_LAYOUT = {
  'id': 'vi_tcvn',
  'title': 'Ti\u1EBFng Vi\u1EC7t TCVN 6064',
  'mappings': {
    '': {
      '': '`\u0103\u00E2\u00EA\u00F4\u0300\u0309\u0303\u0301\u0323' +
          '\u0111-\u20AB' +
          'qwertyuiop\u01B0\u01A1\\' +
          'asdfghjkl;\'' +
          'zxcvbnm,./'
    },
    's': {
      '': '~\u0102\u00C2\u00CA\u00D4\u0300\u0309\u0303\u0301\u0323\u0110_+' +
          'QWERTYUIOP\u01AF\u01A0|' +
          'ASDFGHJKL:"' +
          'ZXCVBNM<>?'
    },
    'l': {
      '': '`\u0102\u00C2\u00CA\u00D4\u0300\u0309\u0303\u0301\u0323' +
          '\u0110-\u20AB' +
          'QWERTYUIOP\u01AF\u01A0\\' +
          'ASDFGHJKL;\'' +
          'ZXCVBNM,./'
    },
    'sl': {
      '': '~\u0103\u00E2\u00EA\u00F4\u0300\u0309\u0303\u0301\u0323\u0111_+' +
          'qwertyuiop\u01B0\u01A1|' +
          'asdfghjkl:"' +
          'zxcvbnm<>?'
    },
    'c': {
      '': '`1234567890-=' +
          'qwertyuiop[]\\' +
          'asdfghjkl;\'' +
          'zxcvbnm,./'
    },
    'sc,cl,scl': {
      '': '~!@#$%^&*()_+' +
          'QWERTYUIOP[]\\' +
          'ASDFGHJKL;\'' +
          'ZXCVBNM,./'
    }
  },
  'transform': {
    // BEGIN- NFC transform generated by
    // experimental/users/ftang/layoututil/gen_tcvn_6064_nfc.pl
    'A\u0300': '\u00C0',
    'A\u0301': '\u00C1',
    'A\u0303': '\u00C3',
    'E\u0300': '\u00C8',
    'E\u0301': '\u00C9',
    'I\u0300': '\u00CC',
    'I\u0301': '\u00CD',
    'N\u0303': '\u00D1',
    'O\u0300': '\u00D2',
    'O\u0301': '\u00D3',
    'O\u0303': '\u00D5',
    'U\u0300': '\u00D9',
    'U\u0301': '\u00DA',
    'Y\u0301': '\u00DD',
    'a\u0300': '\u00E0',
    'a\u0301': '\u00E1',
    'a\u0303': '\u00E3',
    'e\u0300': '\u00E8',
    'e\u0301': '\u00E9',
    'i\u0300': '\u00EC',
    'i\u0301': '\u00ED',
    'n\u0303': '\u00F1',
    'o\u0300': '\u00F2',
    'o\u0301': '\u00F3',
    'o\u0303': '\u00F5',
    'u\u0300': '\u00F9',
    'u\u0301': '\u00FA',
    'y\u0301': '\u00FD',
    'C\u0301': '\u0106',
    'c\u0301': '\u0107',
    'I\u0303': '\u0128',
    'i\u0303': '\u0129',
    'L\u0301': '\u0139',
    'l\u0301': '\u013A',
    'N\u0301': '\u0143',
    'n\u0301': '\u0144',
    'R\u0301': '\u0154',
    'r\u0301': '\u0155',
    'S\u0301': '\u015A',
    's\u0301': '\u015B',
    'U\u0303': '\u0168',
    'u\u0303': '\u0169',
    'Z\u0301': '\u0179',
    'z\u0301': '\u017A',
    '\u00DC\u001d\u0301': '\u01D7',
    '\u00FC\u001d\u0301': '\u01D8',
    '\u00DC\u001d\u0300': '\u01DB',
    '\u00FC\u001d\u0300': '\u01DC',
    'G\u0301': '\u01F4',
    'g\u0301': '\u01F5',
    'N\u0300': '\u01F8',
    'n\u0300': '\u01F9',
    '\u00C5\u001d\u0301': '\u01FA',
    '\u00E5\u001d\u0301': '\u01FB',
    '\u00C6\u001d\u0301': '\u01FC',
    '\u00E6\u001d\u0301': '\u01FD',
    '\u00D8\u001d\u0301': '\u01FE',
    '\u00F8\u001d\u0301': '\u01FF',
    'B\u0323': '\u1E04',
    'b\u0323': '\u1E05',
    '\u00C7\u001d\u0301': '\u1E08',
    '\u00E7\u001d\u0301': '\u1E09',
    'D\u0323': '\u1E0C',
    'd\u0323': '\u1E0D',
    '\u0112\u001d\u0300': '\u1E14',
    '\u0113\u001d\u0300': '\u1E15',
    '\u0112\u001d\u0301': '\u1E16',
    '\u0113\u001d\u0301': '\u1E17',
    'H\u0323': '\u1E24',
    'h\u0323': '\u1E25',
    '\u00CF\u001d\u0301': '\u1E2E',
    '\u00EF\u001d\u0301': '\u1E2F',
    'K\u0301': '\u1E30',
    'k\u0301': '\u1E31',
    'K\u0323': '\u1E32',
    'k\u0323': '\u1E33',
    'L\u0323': '\u1E36',
    'l\u0323': '\u1E37',
    'M\u0301': '\u1E3E',
    'm\u0301': '\u1E3F',
    'M\u0323': '\u1E42',
    'm\u0323': '\u1E43',
    'N\u0323': '\u1E46',
    'n\u0323': '\u1E47',
    '\u00D5\u001d\u0301': '\u1E4C',
    '\u00F5\u001d\u0301': '\u1E4D',
    '\u014C\u001d\u0300': '\u1E50',
    '\u014D\u001d\u0300': '\u1E51',
    '\u014C\u001d\u0301': '\u1E52',
    '\u014D\u001d\u0301': '\u1E53',
    'P\u0301': '\u1E54',
    'p\u0301': '\u1E55',
    'R\u0323': '\u1E5A',
    'r\u0323': '\u1E5B',
    'S\u0323': '\u1E62',
    's\u0323': '\u1E63',
    'T\u0323': '\u1E6C',
    't\u0323': '\u1E6D',
    '\u0168\u001d\u0301': '\u1E78',
    '\u0169\u001d\u0301': '\u1E79',
    'V\u0303': '\u1E7C',
    'v\u0303': '\u1E7D',
    'V\u0323': '\u1E7E',
    'v\u0323': '\u1E7F',
    'W\u0300': '\u1E80',
    'w\u0300': '\u1E81',
    'W\u0301': '\u1E82',
    'w\u0301': '\u1E83',
    'W\u0323': '\u1E88',
    'w\u0323': '\u1E89',
    'Z\u0323': '\u1E92',
    'z\u0323': '\u1E93',
    'A\u0323': '\u1EA0',
    'a\u0323': '\u1EA1',
    'A\u0309': '\u1EA2',
    'a\u0309': '\u1EA3',
    '\u00C2\u0301': '\u1EA4',
    '\u00E2\u0301': '\u1EA5',
    '\u00C2\u0300': '\u1EA6',
    '\u00E2\u0300': '\u1EA7',
    '\u00C2\u0309': '\u1EA8',
    '\u00E2\u0309': '\u1EA9',
    '\u00C2\u0303': '\u1EAA',
    '\u00E2\u0303': '\u1EAB',
    '\u0102\u0301': '\u1EAE',
    '\u0103\u0301': '\u1EAF',
    '\u0102\u0300': '\u1EB0',
    '\u0103\u0300': '\u1EB1',
    '\u0102\u0309': '\u1EB2',
    '\u0103\u0309': '\u1EB3',
    '\u0102\u0303': '\u1EB4',
    '\u0103\u0303': '\u1EB5',
    'E\u0323': '\u1EB8',
    'e\u0323': '\u1EB9',
    'E\u0309': '\u1EBA',
    'e\u0309': '\u1EBB',
    'E\u0303': '\u1EBC',
    'e\u0303': '\u1EBD',
    '\u00CA\u0301': '\u1EBE',
    '\u00EA\u0301': '\u1EBF',
    '\u00CA\u0300': '\u1EC0',
    '\u00EA\u0300': '\u1EC1',
    '\u00CA\u0309': '\u1EC2',
    '\u00EA\u0309': '\u1EC3',
    '\u00CA\u0303': '\u1EC4',
    '\u00EA\u0303': '\u1EC5',
    'I\u0309': '\u1EC8',
    'i\u0309': '\u1EC9',
    'I\u0323': '\u1ECA',
    'i\u0323': '\u1ECB',
    'O\u0323': '\u1ECC',
    'o\u0323': '\u1ECD',
    'O\u0309': '\u1ECE',
    'o\u0309': '\u1ECF',
    '\u00D4\u0301': '\u1ED0',
    '\u00F4\u0301': '\u1ED1',
    '\u00D4\u0300': '\u1ED2',
    '\u00F4\u0300': '\u1ED3',
    '\u00D4\u0309': '\u1ED4',
    '\u00F4\u0309': '\u1ED5',
    '\u00D4\u0303': '\u1ED6',
    '\u00F4\u0303': '\u1ED7',
    '\u01A0\u0301': '\u1EDA',
    '\u01A1\u0301': '\u1EDB',
    '\u01A0\u0300': '\u1EDC',
    '\u01A1\u0300': '\u1EDD',
    '\u01A0\u0309': '\u1EDE',
    '\u01A1\u0309': '\u1EDF',
    '\u01A0\u0303': '\u1EE0',
    '\u01A1\u0303': '\u1EE1',
    '\u01A0\u0323': '\u1EE2',
    '\u01A1\u0323': '\u1EE3',
    'U\u0323': '\u1EE4',
    'u\u0323': '\u1EE5',
    'U\u0309': '\u1EE6',
    'u\u0309': '\u1EE7',
    '\u01AF\u0301': '\u1EE8',
    '\u01B0\u0301': '\u1EE9',
    '\u01AF\u0300': '\u1EEA',
    '\u01B0\u0300': '\u1EEB',
    '\u01AF\u0309': '\u1EEC',
    '\u01B0\u0309': '\u1EED',
    '\u01AF\u0303': '\u1EEE',
    '\u01B0\u0303': '\u1EEF',
    '\u01AF\u0323': '\u1EF0',
    '\u01B0\u0323': '\u1EF1',
    'Y\u0300': '\u1EF2',
    'y\u0300': '\u1EF3',
    'Y\u0323': '\u1EF4',
    'y\u0323': '\u1EF5',
    'Y\u0309': '\u1EF6',
    'y\u0309': '\u1EF7',
    'Y\u0303': '\u1EF8',
    'y\u0303': '\u1EF9'
  }
};

// Load the layout and inform the keyboard to switch layout if necessary.
cros_vk_loadme(VI_TCVN_LAYOUT);
